#!/bin/bash
#SBATCH -D ./
#SBATCH -o LOG/netprophet2_masterlog.out
#SBATCH -e LOG/netprophet2_masterlog.err

module load R/3.2.1
module load openmpi

snakemake --unlock
snakemake --cores 2 --latency-wait 172800 
