#!/bin/bash
#SBATCH -D ./
#SBATCH -o LOG/NetProphet2_masterlog_%A.out
#SBATCH -e LOG/NetProphet2_masterlog_%A.err

module load R/3.2.1
module load openmpi

snakemake --unlock
snakemake --cores 2 --latency-wait 172800 -s Snakefile all
